# quizapp/admin.py
from django.contrib import admin
from .models import Question, Result

class QuestionAdmin(admin.ModelAdmin):
    list_display = ('text', 'option1', 'option2', 'option3', 'option4', 'correct_option')
    # Make fields editable directly in the list view if desired
    # list_editable = ('correct_option',)

class ResultAdmin(admin.ModelAdmin):
    list_display = ('user', 'score', 'total_questions', 'percentage', 'timestamp')
    list_filter = ('user', 'timestamp')
    # Make it read-only in admin as results are generated by quiz attempts
    readonly_fields = ('user', 'score', 'total_questions', 'timestamp')

    def has_add_permission(self, request):
        return False # Prevent adding results manually via admin

    def has_change_permission(self, request, obj=None):
        return False # Prevent changing results via admin (allow view/delete)


admin.site.register(Question, QuestionAdmin)
admin.site.register(Result, ResultAdmin)